version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5430:5430'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: mikrotik_remote
    build:
      context: ./
      target: production
    image: mikrotik_remote
    depends_on:
      - db
    ports:
      - 8083:8083
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5430
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local